[INTERNAL] PerformanceTests: Fixes configuration flag for performance test gate  (#3186)
Performance Test gates are failing:
C:\hostedtoolcache\windows\dotnet\dotnet.exe run --project D:\a\1\s\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Performance.Tests\Microsoft.Azure.Cosmos.Performance.Tests.csproj --configuration Release /p:OS=Windows --no-restore -c Release --framework net6.0 --allCategories=GateBenchmark -- -j Short -m --BaselineValidation
System.InvalidOperationException: Option '--configuration' only accepts a single argument but 2 were provided.
at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
at System.CommandLine.Parsing.OptionResult.GetValueOrDefault[T]

It seems that additional flags are no longer supported for dotnet run