OperationCanceledException: Adds Exception Trace as Child  (#3319)
* add exception trace as a child instead of at beginning

* add test to validate diagnostics ordering

* add using statement to consistently dispose the trace